### ISSUE TITLE
Use 2.0 API for user UUID fields

### ISSUE THREAD

**Issue by erikvanzijst** [jaredhanson/passport-bitbucket#3]
`passport-bitbucket/lib/passport-bitbucket/strategy.js` calls `/1.0/user` to get the currently logged in user details. This however is a deprecated API that lacks the `uuid` field and since usernames are mutable, it's generally important clients use the uuid to identify accounts.

Use `/2.0/user` instead.

**Comment by jaredhanson** [comment]
Implemented and released in v2.0.0.
